apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base

namespace: argocd

commonLabels:
  env: app3

commonAnnotations:
  version: 1.4.1

namePrefix:
  app3-

nameSuffix:
  -v1

images:
  - name: nginx
    newName: nginx
    newTag: latest