apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base
resources:
  - pvc.yaml

patchesStrategicMerge:
  - secret.yaml
  - service.yaml

namespace: argocd

commonLabels:
  env: dev
  app: mongo

commonAnnotations:
  version: 1.1.1

configurations:
  - configuration/sealed-secret-config.yaml
  
generatorOptions:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false

secretGenerator:
  - name: mysecret
    type: Opaque

patches:
- target:
    kind: Service
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: mongo-db
- target:
    kind: Deployment
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: mongo
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: mongo
    - op: replace
      path: /spec/template/spec/containers/0/ports
      value: 
      - containerPort: 27017
        name: mongodb
    - op: replace
      path: /kind
      value: StatefulSet
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts
      value:
        - name: mongodb-persistent-storage
          mountPath: /data/db
    - op: add
      path: /spec/template/spec/volumes
      value:
        - name: mongodb-persistent-storage
          persistentVolumeClaim: 
              claimName: "mongodb-pvc"
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
       requests:
         memory: "256Mi"
         cpu: "500m"
       limits:
         memory: "256Mi"
         cpu: "500m"



nameSuffix:
  -v1

images:
  - name: nginx
    newName: mongo
    newTag: latest