apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base
resources:
  - pvc.yaml
#  - secret.yaml

namespace: argocd

commonLabels:
  env: dev
  app: mongo

commonAnnotations:
  version: 1.1.1

patches:
- target:
    kind: Deployment
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: mongo
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: mongo
    - op: replace
      path: /spec/template/spec/containers/0/ports
      value: 27017
    - op: replace
      path: /kind
      value: StatefulSet
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts
      value:
        - name: mongodb-persistent-storage
          mountPath: /data/db
    - op: add
      path: /spec/template/spec/volumes
      value:
        - name: mongodb-persistent-storage
          persistentVolumeClaim: 
              claimName: "mongodb-pvc"




nameSuffix:
  -v1

images:
  - name: nginx
    newName: mongo
    newTag: latest