apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base

namespace: argocd

patchesStrategicMerge:
  - secret.yaml
  - deployment.yaml

commonLabels:
  env: app4

commonAnnotations:
  version: 1.4.1

namePrefix:
  app4-

nameSuffix:
  -v1

configurations:
  - configuration/sealed-secret-config.yaml
  
generatorOptions:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"
    argocd.argoproj.io/compare-options: IgnoreExtraneous

secretGenerator:
  - name: mysecret
    type: Opaque
#    env: sample-secret.txt

images:
  - name: nginx
    newName: nginx
    newTag: latest