apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base

namespace: argocd

patchesStrategicMerge:
  - secret.yaml

commonLabels:
  env: app4

commonAnnotations:
  version: 1.4.1

namePrefix:
  app4-

nameSuffix:
  -v1

images:
  - name: nginx
    newName: nginx
    newTag: latest