apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: mysecret
  namespace: C:\Users\Marko\.ssh\kubeseal.pem
spec:
  encryptedData:
    password: AgADkQPGau2harWXmR9zYULSamq8m4Px89jGXTdyd329CtDr1hoYJJrnfQb9UAY+wVj+rxO/7BY/UbgzBMeWlo3G/0VNcQjgwkBZvRI5con3ZpsK1CFfo4ceOwfjtuX2fv6l3YN2WOSZRlc6S9mjakWrwcO862RfQCUxv64Y/RRPdsdCb0UlDPgmbMUeMkp6VPkjvWf2wYhvl47sEHn2cspu5SwpQYfulyS4dKx7EXXBIRYZfcjBCMVPNyKtS0RuCmnzoWvQNmmP/zWutqpsUBdZiT8idjQIb4iK09LPv+33wcsG2NnrnTYTF0lhv82bRSJWszPVMjpT0rHE7WnrTTEuO0OsAAjkOHG20/bGDRg3SWtf0Fl9tYYeHuiG6iQibDPlkPp1Rvy4cYJZuKE6QkU/kcEFkIyH37V85wA2AeXh5ejATx+ENXQpo37l5yswn3AdfJeBsJHSdPUHTxLzPmFafLmW6VUSkLcOs7zRKkpEAJJMhSaVIzbEkkKP01AwUV7VyXy2Xkr1W08IthNgFOax2L05f96T8+H0xIwKseYWMiuelH9NfwBFmblol3wFH0xKtazYveqIP8A569d2U7qYBsDDXgCvva4rnIs9Zsag/4fFitmof0pnpfNuZzYax+gh30oiktdLYm7106ed/eDxYNszFTMN9KvbrBZylgESEfdYQULMP3+WhPIiDHImPi/100NUATg8y/Ooc0w=
    username: AgCYwHaQlWfmoW/EDXJXzl7tj0NU64VJCvkC7rPl9faWJVvNsA+64VEyVOUKE2ZfJerYbBtdvC54mwWbtmvNFiAGmOxsSZa3NjEE36+5RUyGyvVLc6ZBiaBXLZyI4vtUuuqNJyVE7fbO2Hwu6+7tylVY08B2FKv48GHmzNzSAyCfnpb3NOfmQYYOKRCXEUerBNj7tXI7S38YgHHDcx6v2fw+vFxxQ03R11qkf66Lym9jXtnndJPboqd6eO6VtrTGwmTmoNlJmhYtdQxzjb1UGPAcGZJJ86VU7NrI6s9Var2mTcYknseGmd/cVI2rX39AqpaHnygpB5ZOlyuDzEqfPn76nsKUc6Kx9h8zd56AqBiwt2gjaAi2vQPdzAn+Y7WXjjNUJsPVX0hpC4AqsshTQbwiW7rJYCrG9S4YiInZ6nuabOQXhAKapIYqPXbaIHShX1cya8IkdncEvLm/u3xtgxhomuJzDFbJ3SnWu1VFAFOIbXp9wuwAClJyO5ACRRCOh71thiP+hwHEAByNXuu6gaF3rGMHvBBJSPXNJSzLMh/qww+TnTpOKkkP30zXyEN68OeGVyoyj29EkD2GT2QmMCZnzZRO0hHj+w9+Bvl11/7mCq0ew6d9Rzoqt14pqWjU/q7f6xBU2zI2Wa7jolryjghuir6dDPyRj31wxMgQN/rGz46zWPoafgPlWqz0iM9kjkN7CoHqiw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: exampleSecret
      namespace: C:\Users\Marko\.ssh\kubeseal.pem
    type: Opaque
status: {}