apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base

namespace: dev

commonLabels:
  env: dev

commonAnnotations:
  version: 1.4.1

namePrefix:
  dev-

nameSuffix:
  -v1

patchesStrategicMerge:
  - rollout-replica.yaml
  - hpa.yaml
  - ingress.yaml

images:
  - name: nginx
    newName: gitlab.bbdev.team:5050/exps/test-python-app
    newTag: 1.4.1