apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base

namespace: dev

commonLabels:
  env: dev

commonAnnotations:
  version: 1.4.1

namePrefix:
  dev-

nameSuffix:
  -v1

images:
  - name: nginx
    newName: nginx
    newTag: latest