apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base

namespace: default

commonLabels:
  env: app2

commonAnnotations:
  version: 1.4.1

namePrefix:
  app2-

nameSuffix:
  -v1

images:
  - name: nginx
    newName: nginx
    newTag: latest